### ISSUE TITLE
vignette building failure

### ISSUE THREAD

**Issue by maelle** [ropensci/restez#47]
https://github.com/r-universe/ropensci/actions/runs/3306156572/jobs/5456837407 (via https://ropensci.r-universe.dev/ui#builds)

```r
Reading 'vignettes/restez.Rmd'
-- RMarkdown error -------------------------------------------------------------
--------------------------------------------------------------------------------
Error in render_rmarkdown(pkg, input = input, output = output_file, output_format = format,  : 
  Failed to render RMarkdown
Caused by error:
! error in callr subprocess
Caused by error:
! rapi_prepare: Failed to prepare query SELECT count(*) FROM nucleotide
Error: Catalog Error: Table with name nucleotide does not exist!
Did you mean "duckdb_types"?
LINE 1: SELECT count(*) FROM nucleotide
```

**Comment by maelle** [comment]
@joelnitta

**Comment by joelnitta** [comment]
@maelle Thanks for filing the issue, I'll check it out soon

**Comment by joelnitta** [comment]
@maelle The root cause of the problem seems to be that the [latest GenBank release](https://ftp.ncbi.nlm.nih.gov/genbank/) chopped off some file names in their [release notes](https://ftp.ncbi.nlm.nih.gov/genbank/gbrel.txt), e.g.:

```
 286199717     gbpln100.seq
 461617634     gbpln1000.se
```

(The second one should be `gbpln1000.seq`, not `gbpln1000.se`) Apparently they weren't expecting to go over 3 digits in that part of the flatfile name!

Working on a patch now...

**Comment by maelle** [comment]
Thank you :rocket:

**Comment by joelnitta** [comment]
Thank you for pointing it out!
